name: Test and Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: cms-dashboard/package-lock.json

      - name: Install dependencies
        run: |
          cd cms-dashboard
          npm ci

      - name: Run tests
        run: |
          cd cms-dashboard
          npm test -- --coverage

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: cms-dashboard/coverage

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'blog-cms-platform'
          path: 'cms-dashboard'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload dependency check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  publish-results:
    needs: [test, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Generate combined report
        run: |
          echo "# Test and Security Scan Results" > combined-report.md
          echo "## Test Coverage" >> combined-report.md
          cat coverage-report/lcov-report/index.html >> combined-report.md
          echo "\n## Security Scan Results" >> combined-report.md
          cat dependency-check-report/dependency-check-report.html >> combined-report.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: combined-report.md
          name: Test and Security Report ${{ github.sha }}
          body_path: combined-report.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
